/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mlib_mpstack_mpstack */

#ifndef _Included_mlib_mpstack_mpstack
#define _Included_mlib_mpstack_mpstack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mlib_mpstack_mpstack
 * Method:    native_create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mlib_mpstack_mpstack_native_1create
  (JNIEnv *, jobject);

/*
 * Class:     mlib_mpstack_mpstack
 * Method:    native_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mlib_mpstack_mpstack_native_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     mlib_mpstack_mpstack
 * Method:    encode
 * Signature: (Lmlib/mpstack/mpstack_pack;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_mlib_mpstack_mpstack_encode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     mlib_mpstack_mpstack
 * Method:    decode
 * Signature: ([B)Lmlib/mpstack/mpstack_pack;
 */
JNIEXPORT jobject JNICALL Java_mlib_mpstack_mpstack_decode
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
